/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: saliam (https://sketchfab.com/saliam0899)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/skyrim-logo-ba0828255db145a395cb170ef7d5378e
title: Skyrim logo
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
  };
};

export function Logo(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/scene.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.01, 8.91, 2.16]} rotation={[-0.27, 0.6, 1.93]} />
        <group rotation={[0, 0.79, 0]} scale={[2.97, 0.4, 2.94]}>
          <mesh
            geometry={nodes.Cube_0.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
